export type DeepSkyObject = {
  id: string;
  name: string;
  commonName: { en: string; cz: string };
  type: 'Galaxy' | 'Nebula' | 'Star Cluster' | 'Planetary Nebula';
  ra: number;
  dec: number;
  magnitude: number;
}

export const MESSIER_CATALOG: DeepSkyObject[] = [
  { id: 'M1', name: 'M1', commonName: { en: 'Crab Nebula', cz: 'Krabí mlhovina' }, type: 'Nebula', ra: 5.575, dec: 22.014, magnitude: 8.4 },
  { id: 'M2', name: 'M2', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 21.558, dec: -0.823, magnitude: 6.3 },
  { id: 'M3', name: 'M3', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 13.703, dec: 28.376, magnitude: 6.2 },
  { id: 'M4', name: 'M4', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 16.393, dec: -26.526, magnitude: 5.6 },
  { id: 'M5', name: 'M5', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 15.31, dec: 2.081, magnitude: 5.6 },
  { id: 'M6', name: 'M6', commonName: { en: 'Butterfly Cluster', cz: 'Motýlí hvězdokupa' }, type: 'Star Cluster', ra: 17.668, dec: -32.217, magnitude: 4.2 },
  { id: 'M7', name: 'M7', commonName: { en: 'Ptolemy Cluster', cz: 'Ptolemaiova hvězdokupa' }, type: 'Star Cluster', ra: 17.898, dec: -34.817, magnitude: 3.3 },
  { id: 'M8', name: 'M8', commonName: { en: 'Lagoon Nebula', cz: 'Mlhovina Laguna' }, type: 'Nebula', ra: 18.063, dec: -24.383, magnitude: 6.0 },
  { id: 'M11', name: 'M11', commonName: { en: 'Wild Duck Cluster', cz: 'Hvězdokupa Divoká kachna' }, type: 'Star Cluster', ra: 18.852, dec: -6.267, magnitude: 6.3 },
  { id: 'M13', name: 'M13', commonName: { en: 'Hercules Cluster', cz: 'Hvězdokupa v Herkulovi' }, type: 'Star Cluster', ra: 16.695, dec: 36.46, magnitude: 5.8 },
  { id: 'M16', name: 'M16', commonName: { en: 'Eagle Nebula', cz: 'Orlí mlhovina' }, type: 'Nebula', ra: 18.313, dec: -13.783, magnitude: 6.0 },
  { id: 'M17', name: 'M17', commonName: { en: 'Omega Nebula', cz: 'Mlhovina Omega' }, type: 'Nebula', ra: 18.347, dec: -16.183, magnitude: 7.0 },
  { id: 'M20', name: 'M20', commonName: { en: 'Trifid Nebula', cz: 'Mlhovina Trifid' }, type: 'Nebula', ra: 18.043, dec: -23.033, magnitude: 6.3 },
  { id: 'M27', name: 'M27', commonName: { en: 'Dumbbell Nebula', cz: 'Mlhovina Činka' }, type: 'Planetary Nebula', ra: 19.993, dec: 22.721, magnitude: 7.5 },
  { id: 'M31', name: 'M31', commonName: { en: 'Andromeda Galaxy', cz: 'Galaxie v Andromedě' }, type: 'Galaxy', ra: 0.7123, dec: 41.269, magnitude: 3.44 },
  { id: 'M33', name: 'M33', commonName: { en: 'Triangulum Galaxy', cz: 'Galaxie v Trojúhelníku' }, type: 'Galaxy', ra: 1.56, dec: 30.66, magnitude: 5.7 },
  { id: 'M42', name: 'M42', commonName: { en: 'Orion Nebula', cz: 'Mlhovina v Orionu' }, type: 'Nebula', ra: 5.5881, dec: -5.391, magnitude: 4.0 },
  { id: 'M44', name: 'M44', commonName: { en: 'Beehive Cluster', cz: 'Jesličky' }, type: 'Star Cluster', ra: 8.67, dec: 19.67, magnitude: 3.7 },
  { id: 'M45', name: 'M45', commonName: { en: 'Pleiades', cz: 'Plejády' }, type: 'Star Cluster', ra: 3.7836, dec: 24.11, magnitude: 1.6 },
  { id: 'M51', name: 'M51', commonName: { en: 'Whirlpool Galaxy', cz: 'Vírová galaxie' }, type: 'Galaxy', ra: 13.498, dec: 47.195, magnitude: 8.4 },
  { id: 'M57', name: 'M57', commonName: { en: 'Ring Nebula', cz: 'Prstencová mlhovina' }, type: 'Planetary Nebula', ra: 18.893, dec: 33.029, magnitude: 8.8 },
  { id: 'M81', name: 'M81', commonName: { en: "Bode's Galaxy", cz: 'Bodeho galaxie' }, type: 'Galaxy', ra: 9.926, dec: 69.065, magnitude: 6.94 },
  { id: 'M82', name: 'M82', commonName: { en: 'Cigar Galaxy', cz: 'Doutníková galaxie' }, type: 'Galaxy', ra: 9.931, dec: 69.682, magnitude: 8.41 },
  { id: 'M101', name: 'M101', commonName: { en: 'Pinwheel Galaxy', cz: 'Větrník' }, type: 'Galaxy', ra: 14.05, dec: 54.35, magnitude: 7.9 },
  { id: 'M104', name: 'M104', commonName: { en: 'Sombrero Galaxy', cz: 'Galaxie Sombrero' }, type: 'Galaxy', ra: 12.67, dec: -11.62, magnitude: 8.0 },
  // ... more objects are available in the background search/log
];

export const TRANSLATIONS = {
  en: {
    title: 'Deep Sky Planner',
    location: 'Location',
    dateTime: 'Date & Time',
    weather: 'Atmospheric Engine',
    clear: 'Clear',
    humidity: 'Humidity',
    seeing: 'Seeing',
    excellent: 'Excellent',
    altitudeChart: 'Altitude Chart',
    over24h: 'over 24h',
    filters: 'Filters',
    type: 'Type',
    all: 'All',
    galaxy: 'Galaxy',
    nebula: 'Nebula',
    starCluster: 'Star Cluster',
    planetaryNebula: 'Planetary Nebula',
    maxMag: 'Max Magnitude',
    search: 'Search...',
    objects: 'Observation Catalog',
    darkSkyMap: 'Dark Sky Map',
    alt: 'Alt',
    az: 'Az',
    footer: 'Deep Sky Planner - Professional Astronomical Planning',
    moonPhase: 'Moon Phase',
    sunTimes: 'Sun & Twilight',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    twilight: 'Astro Twilight',
    searchPlaceholder: 'Search 110 Messier objects...',
    logbook: 'Observation Log',
    addToPlan: 'Add to Plan',
    removeFromPlan: 'Remove',
    notes: 'Observation Notes',
    saveNote: 'Save',
    nightPlan: 'Tonight\'s Night Plan',
    imaging: 'Deep Sky Imaging (Aladin Lite)',
    transparency: 'Transparency',
    cloudCover: 'Cloudy',
  },
  cz: {
    title: 'Hvězdný Plánovač',
    location: 'Lokalita',
    dateTime: 'Datum a čas',
    weather: 'Atmosférické podmínky',
    clear: 'Jasno',
    humidity: 'Vlhkost',
    seeing: 'Klid atmosféry',
    excellent: 'Excelentní',
    altitudeChart: 'Graf výšky',
    over24h: 'za 24h',
    filters: 'Filtry',
    type: 'Typ',
    all: 'Všechny',
    galaxy: 'Galaxie',
    nebula: 'Mlhoviny',
    starCluster: 'Hvězdokupy',
    planetaryNebula: 'Planetární mlhoviny',
    maxMag: 'Max. magnituda',
    search: 'Hledat...',
    objects: 'Katalog objektů',
    darkSkyMap: 'Mapa světelného znečištění',
    alt: 'Vyska',
    az: 'Azim',
    footer: 'Hvězdný Plánovač - Profesionální astronomické plánování',
    moonPhase: 'Fáze Měsíce',
    sunTimes: 'Slunce a soumrak',
    sunrise: 'Východ',
    sunset: 'Západ',
    twilight: 'Astro soumrak',
    searchPlaceholder: 'Hledejte ve 110 Messierových objektech...',
    logbook: 'Deník pozorování',
    addToPlan: 'Přidat do plánu',
    removeFromPlan: 'Odebrat',
    notes: 'Poznámky k pozorování',
    saveNote: 'Uložit',
    nightPlan: 'Plán na dnešní noc',
    imaging: 'Zobrazení objektu (Aladin Lite)',
    transparency: 'Průzračnost',
    cloudCover: 'Zataženo',
  }
}
