export type DeepSkyObject = {
  id: string;
  name: string;
  commonName: { en: string; cz: string };
  type: 'Galaxy' | 'Nebula' | 'Star Cluster' | 'Planetary Nebula' | 'Planet';
  ra: number;
  dec: number;
  magnitude: number;
  recommendedFilter?: string;
}

export const MESSIER_CATALOG: DeepSkyObject[] = [
  { id: 'M1', name: 'M1', commonName: { en: 'Crab Nebula', cz: 'Krabí mlhovina' }, type: 'Nebula', ra: 5.575, dec: 22.014, magnitude: 8.4, recommendedFilter: 'OIII' },
  { id: 'M2', name: 'M2', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 21.558, dec: -0.823, magnitude: 6.3 },
  { id: 'M31', name: 'M31', commonName: { en: 'Andromeda Galaxy', cz: 'Galaxie v Andromedě' }, type: 'Galaxy', ra: 0.7123, dec: 41.269, magnitude: 3.44 },
  { id: 'M33', name: 'M33', commonName: { en: 'Triangulum Galaxy', cz: 'Galaxie v Trojúhelníku' }, type: 'Galaxy', ra: 1.56, dec: 30.66, magnitude: 5.7 },
  { id: 'M42', name: 'M42', commonName: { en: 'Orion Nebula', cz: 'Mlhovina v Orionu' }, type: 'Nebula', ra: 5.588, dec: -5.39, magnitude: 4.0, recommendedFilter: 'UHC' },
  { id: 'M45', name: 'M45', commonName: { en: 'Pleiades', cz: 'Plejády' }, type: 'Star Cluster', ra: 3.784, dec: 24.11, magnitude: 1.6 },
  { id: 'M51', name: 'M51', commonName: { en: 'Whirlpool Galaxy', cz: 'Vírová galaxie' }, type: 'Galaxy', ra: 13.498, dec: 47.195, magnitude: 8.4, recommendedFilter: 'UHC' },
  { id: 'M57', name: 'M57', commonName: { en: 'Ring Nebula', cz: 'Prstencová mlhovina' }, type: 'Planetary Nebula', ra: 18.893, dec: 33.029, magnitude: 8.8, recommendedFilter: 'OIII' },
  { id: 'M81', name: 'M81', commonName: { en: "Bode's Galaxy", cz: 'Bodeho galaxie' }, type: 'Galaxy', ra: 9.926, dec: 69.065, magnitude: 6.94 },
  { id: 'M82', name: 'M82', commonName: { en: 'Cigar Galaxy', cz: 'Doutníková galaxie' }, type: 'Galaxy', ra: 9.931, dec: 69.682, magnitude: 8.41 },
  { id: 'M101', name: 'M101', commonName: { en: 'Pinwheel Galaxy', cz: 'Větrník' }, type: 'Galaxy', ra: 14.05, dec: 54.35, magnitude: 7.9 },
  { id: 'M104', name: 'M104', commonName: { en: 'Sombrero Galaxy', cz: 'Galaxie Sombrero' }, type: 'Galaxy', ra: 12.67, dec: -11.62, magnitude: 8.0 },
  { id: 'NGC 869', name: 'NGC 869', commonName: { en: 'Double Cluster (h Per)', cz: 'Dvojitá hvězdokupa (h Per)' }, type: 'Star Cluster', ra: 2.316, dec: 57.13, magnitude: 5.3 },
  { id: 'NGC 884', name: 'NGC 884', commonName: { en: 'Double Cluster (chi Per)', cz: 'Dvojitá hvězdokupa (chi Per)' }, type: 'Star Cluster', ra: 2.373, dec: 57.15, magnitude: 6.1 },
  { id: 'NGC 7000', name: 'NGC 7000', commonName: { en: 'North America Nebula', cz: 'Mlhovina Severní Amerika' }, type: 'Nebula', ra: 20.97, dec: 44.33, magnitude: 4.0, recommendedFilter: 'OIII' },
  { id: 'NGC 6960', name: 'NGC 6960', commonName: { en: 'Western Veil Nebula', cz: 'Západní část mlhoviny Řasy' }, type: 'Nebula', ra: 20.75, dec: 30.7, magnitude: 7.0, recommendedFilter: 'OIII' },
  { id: 'NGC 2237', name: 'NGC 2237', commonName: { en: 'Rosette Nebula', cz: 'Mlhovina Rozeta' }, type: 'Nebula', ra: 6.538, dec: 4.98, magnitude: 9.0, recommendedFilter: 'UHC' },
  { id: 'NGC 253', name: 'NGC 253', commonName: { en: 'Sculptor Galaxy', cz: 'Galaxie Sochař' }, type: 'Galaxy', ra: 0.793, dec: -25.29, magnitude: 7.2 },
  { id: 'NGC 4565', name: 'NGC 4565', commonName: { en: 'Needle Galaxy', cz: 'Jehlová galaxie' }, type: 'Galaxy', ra: 12.604, dec: 25.99, magnitude: 9.6 },
  { id: 'NGC 5139', name: 'NGC 5139', commonName: { en: 'Omega Centauri', cz: 'Omega Centauri' }, type: 'Star Cluster', ra: 13.448, dec: -47.48, magnitude: 3.9 },
  { id: 'NGC 6357', name: 'NGC 6357', commonName: { en: 'War and Peace Nebula', cz: 'Mlhovina Válka a mír' }, type: 'Nebula', ra: 17.41, dec: -34.2, magnitude: 10.0, recommendedFilter: 'UHC' },
  { id: 'NGC 7293', name: 'NGC 7293', commonName: { en: 'Helix Nebula', cz: 'Mlhovina Helix' }, type: 'Planetary Nebula', ra: 22.49, dec: -20.84, magnitude: 7.6, recommendedFilter: 'OIII' },
];

export const METEOR_SHOWERS = [
  { name: { en: 'Quadrantids', cz: 'Kvadrantidy' }, date: 'Jan 03', zhr: 120, radiant: 'Boötes' },
  { name: { en: 'Lyrids', cz: 'Lyridy' }, date: 'Apr 22', zhr: 18, radiant: 'Lyra' },
  { name: { en: 'Perseids', cz: 'Perseidy' }, date: 'Aug 12', zhr: 100, radiant: 'Perseus' },
  { name: { en: 'Orionids', cz: 'Orionidy' }, date: 'Oct 21', zhr: 20, radiant: 'Orion' },
  { name: { en: 'Leonids', cz: 'Leonidy' }, date: 'Nov 17', zhr: 15, radiant: 'Leo' },
  { name: { en: 'Geminids', cz: 'Geminidy' }, date: 'Dec 14', zhr: 150, radiant: 'Gemini' },
];

export const BRIGHT_COMETS = [
  { name: 'C/2023 A3 (Tsuchinshan-ATLAS)', mag: 4.5, constellation: 'Virgo' },
  { name: '12P/Pons-Brooks', mag: 5.2, constellation: 'Andromeda' },
  { name: 'C/2021 S3 (PANSTARRS)', mag: 9.1, constellation: 'Cygnus' },
];

export const MOON_CRATERS = [
  { name: 'Tycho', age: 10, description: { en: 'Prominent ray system', cz: 'Výrazný systém paprsků' } },
  { name: 'Copernicus', age: 9, description: { en: 'Classic terraced walls', cz: 'Klasické terasovité stěny' } },
  { name: 'Plato', age: 8, description: { en: 'Dark lava-filled floor', cz: 'Tmavé dno vyplněné lávou' } },
  { name: 'Clavius', age: 11, description: { en: 'Massive crater with mini-craters', cz: 'Masivní kráter s řetězcem menších kráterů' } },
  { name: 'Gassendi', age: 12, description: { en: 'Beautiful rilles on floor', cz: 'Krásné brázdy na dně' } },
  { name: 'Theophilus', age: 5, description: { en: 'Sharp central peak', cz: 'Ostrý centrální vrchol' } },
];

export const TRANSLATIONS = {
  en: {
    title: 'Deep Sky Planner',
    location: 'Location',
    dateTime: 'Date & Time',
    weather: 'Atmospheric Conditions',
    clear: 'Clear',
    humidity: 'Humidity',
    seeing: 'Seeing',
    excellent: 'Excellent',
    altitudeChart: 'Altitude Chart',
    over24h: 'over 24h',
    filters: 'Filters',
    type: 'Type',
    all: 'All',
    galaxy: 'Galaxy',
    nebula: 'Nebula',
    starCluster: 'Star Cluster',
    planetaryNebula: 'Planetary Nebula',
    maxMag: 'Max Magnitude',
    search: 'Search...',
    objects: 'Observation Catalog',
    darkSkyMap: 'Dark Sky Map',
    alt: 'Alt',
    az: 'Az',
    footer: 'Deep Sky Planner - Professional Astronomical Planning',
    moonPhase: 'Moon Phase',
    sunTimes: 'Sun & Twilight',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    twilight: 'Astro Twilight',
    searchPlaceholder: 'Search Messier, NGC, IC...',
    logbook: 'Observation Log',
    addToPlan: 'Add to Plan',
    removeFromPlan: 'Remove',
    notes: 'Observation Notes',
    saveNote: 'Save',
    nightPlan: 'Tonight\'s Night Plan',
    imaging: 'Deep Sky Imaging (Aladin Lite)',
    transparency: 'Transparency',
    cloudCover: 'Cloudy',
    cat_all: 'All',
    cat_galaxies: 'Galaxies',
    cat_clusters: 'Star Clusters',
    cat_nebulae: 'Nebulae',
    cat_planets: 'Planets',
    mercury: 'Mercury',
    venus: 'Venus',
    mars: 'Mars',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    uranus: 'Uranus',
    neptune: 'Neptune',
    faq: 'FAQ & Guide',
    backToApp: 'Back to App',
    exportPDF: 'Export to PDF',
    issFlyovers: 'ISS Flyovers',
    iss_none: 'No flyovers in next 24h',
    iss_time: 'Time',
    iss_duration: 'Dur',
    iss_maxAlt: 'Max Alt',
    faq_intro: 'Welcome to the Deep Sky Planner Knowledge Base. This comprehensive guide provides in-depth technical information about celestial mechanics, atmospheric science, and astrophotography principles to help you maximize your observation efficiency.',
    faq_q1: 'Understanding Deep Sky Objects (DSO) & Classification',
    faq_a1: 'Deep Sky Objects are celestial bodies beyond our solar system that are not individual stars. They are categorized into three primary types: 1. GALAXIES: Massive systems of billions of stars, dust, and gas bound by gravity (e.g., M31 Andromeda). 2. NEBULAE: Interstellar clouds where stars are born or die; Emission nebulae glow by their own light, while Dark nebulae block background light. 3. STAR CLUSTERS: Open clusters are young, loosely bound groups (like M45 Pleiades), while Globular clusters are ancient, densely packed spherical groups of hundreds of thousands of stars. Understanding the surface brightness of these objects is crucial, as a large nebula with a low magnitude may be harder to see than a small, bright star cluster.',
    faq_q2: 'Atmospheric Physics: Seeing, Transparency & Twilight',
    faq_a2: 'Successful observation depends heavily on the atmosphere. SEEING refers to the stability of the air; high turbulence causes stars to twinkle and blurs fine details in planets. It is measured in arcseconds (FWHM). TRANSPARENCY describes how clear the air is from dust and moisture; high humidity or aerosols can scatter light even if the sky is cloudless. TWILIGHT has three stages: Civil (Sun at -6°), Nautical (-12°), and Astronomical (-18°). Deep sky imaging should only occur during "True Night" (Astronomical Twilight), when the Sun is more than 18 degrees below the horizon, ensuring the background sky is at its darkest level allowed by natural physics.',
    faq_q3: 'Celestial Coordinates & Observation Windows',
    faq_a3: 'The sky is mapped using Equatorial coordinates: Right Ascension (RA) and Declination (Dec), similar to longitude and latitude on Earth. However, for immediate planning, we use Altitude (Alt) and Azimuth (Az). ALTITUDE is the most critical metric: 0° is the horizon, 90° is the Zenith. Observing objects below 30° is inefficient because you are looking through significantly more atmosphere (Air Mass), which degrades image quality and brightness. The "Transit" is the moment an object reaches its highest point in the sky for the night, providing the best possible viewing conditions.',
    faq_q4: 'The Science of Magnitude and Surface Brightness',
    faq_a4: 'Magnitude is a logarithmic scale of brightness. A difference of 5 magnitudes equals a factor of 100 in brightness. IMPORTANT: The scale is inverse—lower numbers are brighter (e.g., Venus at -4.4 vs Neptune at +7.8). However, for DSOs, Magnitude can be misleading. "Integrated Magnitude" spreads the light of a large galaxy over its entire area. Therefore, a Mag 9 galaxy might be invisible in a telescope that easily sees a Mag 9 star. This is why "Surface Brightness" (Mag per square arcsec) is often a better indicator of how difficult a galaxy or nebula will be to observe under light-polluted skies.',
    faq_q5: 'Astrophotography: Sampling, FOV and Sensor Metrics',
    faq_a5: 'Precision imaging requires matching your camera pixel size to your telescopes focal length. IMAGE SCALE (arcsec/pixel) determines your resolution. If your scale is too low (<0.6"/px), you are OVERSAMPLING—enlarging the image but gaining no new detail because atmospheric seeing limits the resolution. If it is too high (>2.0"/px), you are UNDERSAMPLING—stars will appear square and details will be lost. Ideally, aim for 1.0" to 1.5"/px for most locations. FIELD OF VIEW (FOV) is the area of sky captured by your sensor; larger sensors or shorter focal lengths provide a wider context, essential for massive nebulae like North America or Andromeda.',
    faq_q6: 'Filters & Signal-to-Noise Ratio (SNR) Optimization',
    faq_a6: 'To combat light pollution and enhance contrast, we use specialized filters. UHC (Ultra High Contrast) filters block street lights while passing critical H-beta and OIII wavelengths. OIII (Oxygen III) filters are even narrower, isolating ionized oxygen lines common in planetary nebulae and supernova remnants. For galaxies, which emit light across the full spectrum (Broadband), light pollution filters are less effective and may even hurt your signal. Improving your SNR is the ultimate goal: this is achieved by increasing "Total Integration Time"—the sum of all your exposures. Doubling your SNR requires four times as much exposure data.',
    telescopeControl: 'ASCOM Alpaca Telescope',
    connect: 'Connect',
    disconnect: 'Disconnect',
    slewTo: 'Slew Telescope',
    community: 'Community',
    planner: 'Planner',
    loginSync: 'Cloud Sync',
    shareObservation: 'Share Observation',
    sharedBy: 'Shared by',
    ipAddress: 'IP Address',
    connected: 'Connected',
    nightMode: 'Red Night Mode',
    gearSimulator: 'Gear Simulator',
    focalLength: 'Focal Length (mm)',
    eyepiece: 'Eyepiece (mm)',
    magnification: 'Magnification',
    exitPupil: 'Exit Pupil',
    meteorShowers: 'Meteor Showers',
    recommendedFilter: 'Recommended Filter',
    comets: 'Bright Comets',
    peakDate: 'Peak',
    mm: 'mm',
    starMap: 'Interactive Sky Map',
    pixelSize: 'Pixel Size (μm)',
    resolution: 'Resolution',
    exposure: 'Est. Exposure',
    astroAsst: 'Astro-Photo Assistant',
    moonAsst: 'Moon & Terminator',
    visibleCraters: 'Best visible craters today',
    issLive: 'Live ISS Tracker',
    sensorRes: 'Sensor Res (px)',
    sampling: 'Sampling Rate',
    guiding: 'Req. Guiding RMS',
    integration: 'Total Data Req.',
    optimal: 'Optimal',
    undersampled: 'Under-sampled',
    oversampled: 'Over-sampled',
    aperture: 'Aperture (mm)',
    eyepieceAfov: 'Eyepiece AFOV (°)',
    tfov: 'True FOV',
    dawesLimit: 'Resolving Power',
    limitingMag: 'Limiting Mag',
    lightGain: 'Light Gain',
    mountPos: 'Mount Position',
    tracking: 'Tracking',
    park: 'Park',
    abort: 'Abort',
    sync: 'Sync',
    slewing: 'Slewing...',
    slew: 'Slew',
    generated: 'Generated',
    hoursShort: 'h',
    target: 'Target',
    bortleScale: 'Bortle Scale & Sky Quality',
    bortleClass: 'Bortle Class',
    sqmValue: 'Est. SQM',
    nakedEyeStars: 'Naked Eye Stars',
    bortle1: 'Excellent dark-sky site',
    bortle2: 'Typical truly dark site',
    bortle3: 'Rural sky',
    bortle4: 'Rural/suburban transition',
    bortle5: 'Suburban sky',
    bortle6: 'Bright suburban sky',
    bortle7: 'Suburban/urban transition',
    bortle8: 'City sky',
    bortle9: 'Inner-city sky',
    north: 'N',
    south: 'S',
    east: 'E',
    west: 'W',
    zenith: 'Zenith',
    horizon: 'Horizon',
    celestialRegistry: 'Celestial Registry',
    discovery: 'Discovery & History',
    wikiLoading: 'Querying NASA/Wiki database...',
    wikiError: 'Telemetry data not available.',
  },
  cz: {
    title: 'Hvězdný Plánovač',
    location: 'Lokalita',
    dateTime: 'Datum a čas',
    weather: 'Atmosférické podmínky',
    clear: 'Jasno',
    humidity: 'Vlhkost',
    seeing: 'Klid atmosféry',
    excellent: 'Excelentní',
    altitudeChart: 'Graf výšky',
    over24h: 'za 24h',
    filters: 'Filtry',
    type: 'Typ',
    all: 'Všechny',
    galaxy: 'Galaxie',
    nebula: 'Mlhoviny',
    starCluster: 'Hvězdokupy',
    planetaryNebula: 'Planetární mlhoviny',
    maxMag: 'Max. magnituda',
    search: 'Hledat...',
    objects: 'Katalog objektů',
    darkSkyMap: 'Mapa světelného znečištění',
    alt: 'Vyska',
    az: 'Azim',
    footer: 'Hvězdný Plánovač - Profesionální astronomické plánování',
    moonPhase: 'Fáze Měsíce',
    sunTimes: 'Sluneční události',
    sunrise: 'Východ',
    sunset: 'Západ',
    twilight: 'Astro soumrak',
    searchPlaceholder: 'Hledejte Messier, NGC, IC...',
    logbook: 'Deník pozorování',
    addToPlan: 'Přidat do plánu',
    removeFromPlan: 'Odebrat',
    notes: 'Poznámky k pozorování',
    saveNote: 'Uložit',
    nightPlan: 'Plán na dnešní noc',
    imaging: 'Zobrazení objektu (Aladin Lite)',
    transparency: 'Průzračnost',
    cloudCover: 'Zataženo',
    cat_all: 'Vše',
    cat_galaxies: 'Galaxie',
    cat_clusters: 'Hvězdokupy',
    cat_nebulae: 'Mlhoviny',
    cat_planets: 'Planety',
    mercury: 'Merkur',
    venus: 'Venuše',
    mars: 'Mars',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    uranus: 'Uran',
    neptune: 'Neptun',
    faq: 'FAQ & Průvodce',
    backToApp: 'Zpět do aplikace',
    exportPDF: 'Exportovat do PDF',
    issFlyovers: 'Přelety ISS',
    iss_none: 'Žádné přelety v příštích 24h',
    iss_time: 'Čas',
    iss_duration: 'Délka',
    iss_maxAlt: 'Max. výška',
    faq_intro: 'Vítejte v technické znalostní bázi Hvězdného Plánovače. Tento průvodce poskytuje hloubkové informace o nebeské mechanice, fyzice atmosféry a principech astrofotografie, které vám pomohou vytěžit z každé jasné noci maximum.',
    faq_q1: 'Klasifikace Deep Sky objektů (DSO)',
    faq_a1: 'Deep Sky objekty jsou tělesa mimo naši sluneční soustavu, která nejsou jednotlivými hvězdami. Rozdělujeme je do tří hlavních kategorií: 1. GALAXIE: Obrovské systémy miliard hvězd, prachu a plynu vázané gravitací (např. M31 v Andromedě). 2. MLHOVINY: Mezihvězdná mračna, kde hvězdy vznikají nebo zanikají; emisní mlhoviny svítí vlastním světlem, zatímco temné mlhoviny blokují světlo pozadí. 3. HVĚZDOKUPY: Otevřené jsou mladé, volně vázané skupiny (jako M45 Plejády), kulové jsou prastaré, husté sférické systémy statisíců hvězd. U DSO je klíčový pojem "povrchová jasnost"—velká mlhovina s nízkou magnitudou může být hůře viditelná než malá, jasná hvězdokupa.',
    faq_q2: 'Fyzika atmosféry: Seeing, Průzračnost a Soumrak',
    faq_a2: 'Úspěch pozorování závisí na stavu atmosféry. SEEING (Klid atmosféry) označuje stabilitu vzduchu; vysoká turbulence způsobuje chvění hvězd a rozmazává detaily planet. Měří se v úhlových vteřinách (FWHM). PRŮZRAČNOST popisuje čistotu vzduchu od prachu a vlhkosti; vysoká vlhkost rozptyluje světlo i při bezmračné obloze. SOUMRAK má tři fáze: Občanský (Slunce -6°), Navigační (-12°) a Astronomický (-18°). Skutečná tma nastává až při astronomickém soumraku, kdy je pozadí oblohy nejtmavší a umožňuje sledování nejvzdálenějších objektů.',
    faq_q3: 'Nebeské souřadnice a pozorovací okna',
    faq_a3: 'Obloha je mapována pomocí rovníkových souřadnic: Rektascenze (RA) a Deklinace (Dec). Pro praktické plánování však používáme výšku nad obzorem (Alt) a Azimut (Az). VÝŠKA je nejdůležitější: 0° je horizont, 90° je Zenit. Pozorování objektů pod 30° je neefektivní, protože se díváte přes obrovskou masu vzduchu (Air Mass), která pohlcuje světlo a zhoršuje obraz. Nejlepší čas pro pozorování je tzv. "Kulminace" (Transit), kdy objekt dosahuje svého nejvyššího bodu na obloze.',
    faq_q4: 'Věda o Magnitudě a Povrchovém jasu',
    faq_a4: 'Magnituda je logaritmická škála jasu. Rozdíl 5 magnitud odpovídá 100násobnému rozdílu v jasu. Stupnice je inverzní—nižší čísla jsou jasnější (Venuše -4.4 vs Neptun +7.8). U plošných objektů (galaxie, mlhoviny) může být magnituda zavádějící. Jde o tzv. "integrovanou magnitudu", která sčítá světlo z celé plochy. Proto může být galaxie s mag 9 neviditelná, zatímco hvězda s mag 9 v okuláru září. Proto v astrofotografii pracujeme spíše s povrchovým jasem (mag na úhlovou vteřinu čtvereční).',
    faq_q5: 'Astrofotografie: Sampling, FOV a parametry senzoru',
    faq_a5: 'Precizní focení vyžaduje sladění velikosti pixelu kamery a ohniska dalekohledu. IMAGE SCALE (arcsec/pixel) určuje vaše rozlišení. Pokud je měřítko příliš nízké (<0.6"/px), dochází k OVERSAMPLINGU—obraz zvětšujete, ale nezískáváte nové detaily, protože vás omezuje atmosféra. Pokud je příliš vysoké (>2.0"/px), dochází k UNDERSAMPLINGU—hvězdy budou hranaté. Ideální rozmezí je 1.0" až 1.5"/px. FIELD OF VIEW (FOV) je plocha oblohy zachycená senzorem; větší senzory nebo kratší ohniska umožňují fotit rozsáhlé komplexy mlhovin.',
    faq_q6: 'Filtry a optimalizace poměru signálu k šumu (SNR)',
    faq_a6: 'K potlačení světelného znečištění používáme speciální filtry. UHC filtry blokují sodíkové výbojky a propouštějí kritické vlnové délky H-beta a OIII. OIII filtry jsou úzkopásmové a izolují pouze ionizovaný kyslík, typický pro planetární mlhoviny. U galaxií, které září v celém spektru (Broadband), jsou filtry méně účinné a mohou signál i poškodit. Cílem je maximalizovat SNR pomocí "celkového integračního času"—součtu všech expozic. Pro zdvojnásobení SNR potřebujete čtyřikrát více dat.',
    telescopeControl: 'Ovládání teleskopu (ASCOM Alpaca)',
    connect: 'Připojit',
    disconnect: 'Odpojit',
    slewTo: 'Najet teleskopem',
    community: 'Komunita',
    planner: 'Plánovač',
    loginSync: 'Cloud Sync',
    shareObservation: 'Sdílet pozorování',
    sharedBy: 'Sdílel(a)',
    ipAddress: 'IP Adresa',
    connected: 'Připojeno',
    nightMode: 'Noční režim (Červený)',
    gearSimulator: 'Kalkulačka optiky',
    focalLength: 'Ohnisko (mm)',
    eyepiece: 'Okulár (mm)',
    magnification: 'Zvětšení',
    exitPupil: 'Výstupní pupila',
    meteorShowers: 'Meteorické roje',
    recommendedFilter: 'Doporučený filtr',
    comets: 'Jasné komety',
    peakDate: 'Maximum',
    mm: 'mm',
    starMap: 'Interaktivní mapa oblohy',
    pixelSize: 'Velikost pixelu (μm)',
    resolution: 'Rozlišení',
    exposure: 'Odhad expozice',
    astroAsst: 'Astro-foto asistent',
    moonAsst: 'Měsíc a terminátor',
    visibleCraters: 'Dnes nejlépe viditelné krátery',
    issLive: 'Živé sledování ISS',
    sensorRes: 'Rozlišení senzoru (px)',
    sampling: 'Kvalita samplingu',
    guiding: 'Požadovaná pointace (RMS)',
    integration: 'Potřebná data (celkem)',
    optimal: 'Optimální',
    undersampled: 'Under-sampled',
    oversampled: 'Over-sampled',
    aperture: 'Průměr objektivu (mm)',
    eyepieceAfov: 'Zdánlivé pole okuláru (°)',
    tfov: 'Reálné zorné pole',
    dawesLimit: 'Rozlišovací mez',
    limitingMag: 'Mezní magnituda',
    lightGain: 'Světelný zisk',
    mountPos: 'Poloha montáže',
    tracking: 'Sledování',
    park: 'Parkovat',
    abort: 'Zastavit',
    sync: 'Synchronizovat',
    slewing: 'Pohybuji se...',
    target: 'Cíl',
    bortleScale: 'Bortleho stupnice a kvalita oblohy',
    bortleClass: 'Bortleho třída',
    sqmValue: 'Odhad SQM',
    nakedEyeStars: 'Hvězdy viditelné okem',
    bortle1: 'Excelentní tmavá obloha (bez znečištění)',
    bortle2: 'Typicky tmavá lokalita',
    bortle3: 'Venkovská obloha',
    bortle4: 'Přechod venkov/předměstí',
    bortle5: 'Předměstská obloha',
    bortle6: 'Jasná předměstská obloha',
    bortle7: 'Přechod předměstí/město',
    bortle8: 'Městská obloha',
    bortle9: 'Centrum velkoměsta',
    north: 'S',
    south: 'J',
    east: 'V',
    west: 'Z',
    zenith: 'Zenit',
    horizon: 'Obzor',
    celestialRegistry: 'Nebeský registr',
    discovery: 'Objev a historie',
    wikiLoading: 'Dotazuji databázi NASA/Wiki...',
    wikiError: 'Data telemetrie nejsou dostupná.',
  }
}
