export type DeepSkyObject = {
  id: string;
  name: string;
  commonName: { en: string; cz: string };
  type: 'Galaxy' | 'Nebula' | 'Star Cluster' | 'Planetary Nebula' | 'Planet';
  ra: number;
  dec: number;
  magnitude: number;
  recommendedFilter?: string;
}

export const MESSIER_CATALOG: DeepSkyObject[] = [
  { id: 'M1', name: 'M1', commonName: { en: 'Crab Nebula', cz: 'Krabí mlhovina' }, type: 'Nebula', ra: 5.575, dec: 22.014, magnitude: 8.4, recommendedFilter: 'OIII' },
  { id: 'M2', name: 'M2', commonName: { en: 'Globular Cluster', cz: 'Kulová hvězdokupa' }, type: 'Star Cluster', ra: 21.558, dec: -0.823, magnitude: 6.3 },
  { id: 'M31', name: 'M31', commonName: { en: 'Andromeda Galaxy', cz: 'Galaxie v Andromedě' }, type: 'Galaxy', ra: 0.7123, dec: 41.269, magnitude: 3.44 },
  { id: 'M33', name: 'M33', commonName: { en: 'Triangulum Galaxy', cz: 'Galaxie v Trojúhelníku' }, type: 'Galaxy', ra: 1.56, dec: 30.66, magnitude: 5.7 },
  { id: 'M42', name: 'M42', commonName: { en: 'Orion Nebula', cz: 'Mlhovina v Orionu' }, type: 'Nebula', ra: 5.588, dec: -5.39, magnitude: 4.0, recommendedFilter: 'UHC' },
  { id: 'M45', name: 'M45', commonName: { en: 'Pleiades', cz: 'Plejády' }, type: 'Star Cluster', ra: 3.784, dec: 24.11, magnitude: 1.6 },
  { id: 'M51', name: 'M51', commonName: { en: 'Whirlpool Galaxy', cz: 'Vírová galaxie' }, type: 'Galaxy', ra: 13.498, dec: 47.195, magnitude: 8.4, recommendedFilter: 'UHC' },
  { id: 'M57', name: 'M57', commonName: { en: 'Ring Nebula', cz: 'Prstencová mlhovina' }, type: 'Planetary Nebula', ra: 18.893, dec: 33.029, magnitude: 8.8, recommendedFilter: 'OIII' },
  { id: 'M81', name: 'M81', commonName: { en: "Bode's Galaxy", cz: 'Bodeho galaxie' }, type: 'Galaxy', ra: 9.926, dec: 69.065, magnitude: 6.94 },
  { id: 'M82', name: 'M82', commonName: { en: 'Cigar Galaxy', cz: 'Doutníková galaxie' }, type: 'Galaxy', ra: 9.931, dec: 69.682, magnitude: 8.41 },
  { id: 'M101', name: 'M101', commonName: { en: 'Pinwheel Galaxy', cz: 'Větrník' }, type: 'Galaxy', ra: 14.05, dec: 54.35, magnitude: 7.9 },
  { id: 'M104', name: 'M104', commonName: { en: 'Sombrero Galaxy', cz: 'Galaxie Sombrero' }, type: 'Galaxy', ra: 12.67, dec: -11.62, magnitude: 8.0 },
  { id: 'NGC 869', name: 'NGC 869', commonName: { en: 'Double Cluster (h Per)', cz: 'Dvojitá hvězdokupa (h Per)' }, type: 'Star Cluster', ra: 2.316, dec: 57.13, magnitude: 5.3 },
  { id: 'NGC 884', name: 'NGC 884', commonName: { en: 'Double Cluster (chi Per)', cz: 'Dvojitá hvězdokupa (chi Per)' }, type: 'Star Cluster', ra: 2.373, dec: 57.15, magnitude: 6.1 },
  { id: 'NGC 7000', name: 'NGC 7000', commonName: { en: 'North America Nebula', cz: 'Mlhovina Severní Amerika' }, type: 'Nebula', ra: 20.97, dec: 44.33, magnitude: 4.0, recommendedFilter: 'OIII' },
  { id: 'NGC 6960', name: 'NGC 6960', commonName: { en: 'Western Veil Nebula', cz: 'Západní část mlhoviny Řasy' }, type: 'Nebula', ra: 20.75, dec: 30.7, magnitude: 7.0, recommendedFilter: 'OIII' },
  { id: 'NGC 2237', name: 'NGC 2237', commonName: { en: 'Rosette Nebula', cz: 'Mlhovina Rozeta' }, type: 'Nebula', ra: 6.538, dec: 4.98, magnitude: 9.0, recommendedFilter: 'UHC' },
  { id: 'NGC 253', name: 'NGC 253', commonName: { en: 'Sculptor Galaxy', cz: 'Galaxie Sochař' }, type: 'Galaxy', ra: 0.793, dec: -25.29, magnitude: 7.2 },
  { id: 'NGC 4565', name: 'NGC 4565', commonName: { en: 'Needle Galaxy', cz: 'Jehlová galaxie' }, type: 'Galaxy', ra: 12.604, dec: 25.99, magnitude: 9.6 },
  { id: 'NGC 5139', name: 'NGC 5139', commonName: { en: 'Omega Centauri', cz: 'Omega Centauri' }, type: 'Star Cluster', ra: 13.448, dec: -47.48, magnitude: 3.9 },
  { id: 'NGC 6357', name: 'NGC 6357', commonName: { en: 'War and Peace Nebula', cz: 'Mlhovina Válka a mír' }, type: 'Nebula', ra: 17.41, dec: -34.2, magnitude: 10.0, recommendedFilter: 'UHC' },
  { id: 'NGC 7293', name: 'NGC 7293', commonName: { en: 'Helix Nebula', cz: 'Mlhovina Helix' }, type: 'Planetary Nebula', ra: 22.49, dec: -20.84, magnitude: 7.6, recommendedFilter: 'OIII' },
];

export const METEOR_SHOWERS = [
  { name: { en: 'Quadrantids', cz: 'Kvadrantidy' }, date: 'Jan 03', zhr: 120, radiant: 'Boötes' },
  { name: { en: 'Lyrids', cz: 'Lyridy' }, date: 'Apr 22', zhr: 18, radiant: 'Lyra' },
  { name: { en: 'Perseids', cz: 'Perseidy' }, date: 'Aug 12', zhr: 100, radiant: 'Perseus' },
  { name: { en: 'Orionids', cz: 'Orionidy' }, date: 'Oct 21', zhr: 20, radiant: 'Orion' },
  { name: { en: 'Leonids', cz: 'Leonidy' }, date: 'Nov 17', zhr: 15, radiant: 'Leo' },
  { name: { en: 'Geminids', cz: 'Geminidy' }, date: 'Dec 14', zhr: 150, radiant: 'Gemini' },
];

export const BRIGHT_COMETS = [
  { name: 'C/2023 A3 (Tsuchinshan-ATLAS)', mag: 4.5, constellation: 'Virgo' },
  { name: '12P/Pons-Brooks', mag: 5.2, constellation: 'Andromeda' },
  { name: 'C/2021 S3 (PANSTARRS)', mag: 9.1, constellation: 'Cygnus' },
];

export const MOON_CRATERS = [
  { name: 'Tycho', age: 10, description: { en: 'Prominent ray system', cz: 'Výrazný systém paprsků' } },
  { name: 'Copernicus', age: 9, description: { en: 'Classic terraced walls', cz: 'Klasické terasovité stěny' } },
  { name: 'Plato', age: 8, description: { en: 'Dark lava-filled floor', cz: 'Tmavé dno vyplněné lávou' } },
  { name: 'Clavius', age: 11, description: { en: 'Massive crater with mini-craters', cz: 'Masivní kráter s řetězcem menších kráterů' } },
  { name: 'Gassendi', age: 12, description: { en: 'Beautiful rilles on floor', cz: 'Krásné brázdy na dně' } },
  { name: 'Theophilus', age: 5, description: { en: 'Sharp central peak', cz: 'Ostrý centrální vrchol' } },
];

export const TRANSLATIONS = {
  en: {
    title: 'Deep Sky Planner',
    location: 'Location',
    dateTime: 'Date & Time',
    weather: 'Atmospheric Conditions',
    clear: 'Clear',
    humidity: 'Humidity',
    seeing: 'Seeing',
    excellent: 'Excellent',
    altitudeChart: 'Altitude Chart',
    over24h: 'over 24h',
    filters: 'Filters',
    type: 'Type',
    all: 'All',
    galaxy: 'Galaxy',
    nebula: 'Nebula',
    starCluster: 'Star Cluster',
    planetaryNebula: 'Planetary Nebula',
    maxMag: 'Max Magnitude',
    search: 'Search...',
    objects: 'Observation Catalog',
    darkSkyMap: 'Dark Sky Map',
    alt: 'Alt',
    az: 'Az',
    footer: 'Deep Sky Planner - Professional Astronomical Planning',
    moonPhase: 'Moon Phase',
    sunTimes: 'Sun & Twilight',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    twilight: 'Astro Twilight',
    searchPlaceholder: 'Search Messier, NGC, IC...',
    logbook: 'Observation Log',
    addToPlan: 'Add to Plan',
    removeFromPlan: 'Remove',
    notes: 'Observation Notes',
    saveNote: 'Save',
    nightPlan: 'Tonight\'s Night Plan',
    imaging: 'Deep Sky Imaging (Aladin Lite)',
    transparency: 'Transparency',
    cloudCover: 'Cloudy',
    cat_all: 'All',
    cat_galaxies: 'Galaxies',
    cat_clusters: 'Star Clusters',
    cat_nebulae: 'Nebulae',
    cat_planets: 'Planets',
    mercury: 'Mercury',
    venus: 'Venus',
    mars: 'Mars',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    uranus: 'Uranus',
    neptune: 'Neptune',
    faq: 'FAQ & Guide',
    backToApp: 'Back to App',
    exportPDF: 'Export to PDF',
    issFlyovers: 'ISS Flyovers',
    iss_none: 'No flyovers in next 24h',
    iss_time: 'Time',
    iss_duration: 'Dur',
    iss_maxAlt: 'Max Alt',
    faq_intro: 'Welcome to the Deep Sky Planner guide. This tool will help you plan your space observations even if you are a beginner.',
    faq_q1: 'What are Deep Sky objects?',
    faq_a1: 'They are deep space objects that are neither stars nor planets. This includes galaxies (billions of stars), nebulae (clouds of gas and dust), and star clusters (groups of stars). Our catalog contains 110 Messier objects – the most beautiful ones visible with amateur telescopes.',
    faq_q2: 'What does "Altitude" mean?',
    faq_a2: 'It is the angle between the object and your horizontal horizon. 0° means the object is on the horizon, 90° (zenith) means it is directly above your head. For best viewing, look for objects with an altitude above 30°, where the atmosphere is thinnest.',
    faq_q3: 'Why use the Light Pollution Map?',
    faq_a3: 'City lights "wash out" the sky, making faint galaxies invisible. On the map, look for blue and black areas – these are the darkest spots where you will see the universe in its full glory. Red and white areas indicate large cities with poor visibility.',
    faq_q4: 'What is Magnitude?',
    faq_a4: 'It is a scientific measurement of an object\'s brightness. Note: The LOWER the number, the BRIGHTER the object. Sirius has a magnitude of -1.4, while a faint galaxy might be 9.0. The human eye can see objects up to magnitude 6.0 under a dark sky.',
    faq_q5: 'How to use the Altitude Chart?',
    faq_a5: 'The chart shows the movement of the selected object over 24 hours. The highest point on the curve indicates the time when the object is best visible. If the curve is below zero, the object is below the horizon.',
    faq_q6: 'What is Aladin Lite?',
    faq_a6: 'It is an integrated star atlas that shows you REAL photos from professional telescopes. It helps you orient yourself and see what the object looks like before you try to find it with your own telescope.',
    telescopeControl: 'ASCOM Alpaca Telescope',
    connect: 'Connect',
    disconnect: 'Disconnect',
    slewTo: 'Slew Telescope',
    community: 'Community',
    planner: 'Planner',
    loginSync: 'Cloud Sync',
    shareObservation: 'Share Observation',
    sharedBy: 'Shared by',
    ipAddress: 'IP Address',
    connected: 'Connected',
    nightMode: 'Red Night Mode',
    gearSimulator: 'Gear Simulator',
    focalLength: 'Focal Length (mm)',
    eyepiece: 'Eyepiece (mm)',
    magnification: 'Magnification',
    exitPupil: 'Exit Pupil',
    meteorShowers: 'Meteor Showers',
    recommendedFilter: 'Recommended Filter',
    comets: 'Bright Comets',
    peakDate: 'Peak',
    mm: 'mm',
    starMap: 'Interactive Sky Map',
    pixelSize: 'Pixel Size (μm)',
    resolution: 'Resolution',
    exposure: 'Est. Exposure',
    astroAsst: 'Astro-Photo Assistant',
    moonAsst: 'Moon & Terminator',
    visibleCraters: 'Best visible craters today',
    issLive: 'Live ISS Tracker',
    sensorRes: 'Sensor Res (px)',
    sampling: 'Sampling Rate',
    guiding: 'Req. Guiding RMS',
    integration: 'Total Data Req.',
    optimal: 'Optimal',
    undersampled: 'Under-sampled',
    oversampled: 'Over-sampled',
  },
  cz: {
    title: 'Hvězdný Plánovač',
    location: 'Lokalita',
    dateTime: 'Datum a čas',
    weather: 'Atmosférické podmínky',
    clear: 'Jasno',
    humidity: 'Vlhkost',
    seeing: 'Klid atmosféry',
    excellent: 'Excelentní',
    altitudeChart: 'Graf výšky',
    over24h: 'za 24h',
    filters: 'Filtry',
    type: 'Typ',
    all: 'Všechny',
    galaxy: 'Galaxie',
    nebula: 'Mlhoviny',
    starCluster: 'Hvězdokupy',
    planetaryNebula: 'Planetární mlhoviny',
    maxMag: 'Max. magnituda',
    search: 'Hledat...',
    objects: 'Katalog objektů',
    darkSkyMap: 'Mapa světelného znečištění',
    alt: 'Vyska',
    az: 'Azim',
    footer: 'Hvězdný Plánovač - Profesionální astronomické plánování',
    moonPhase: 'Fáze Měsíce',
    sunTimes: 'Sluneční události',
    sunrise: 'Východ',
    sunset: 'Západ',
    twilight: 'Astro soumrak',
    searchPlaceholder: 'Hledejte Messier, NGC, IC...',
    logbook: 'Deník pozorování',
    addToPlan: 'Přidat do plánu',
    removeFromPlan: 'Odebrat',
    notes: 'Poznámky k pozorování',
    saveNote: 'Uložit',
    nightPlan: 'Plán na dnešní noc',
    imaging: 'Zobrazení objektu (Aladin Lite)',
    transparency: 'Průzračnost',
    cloudCover: 'Zataženo',
    cat_all: 'Vše',
    cat_galaxies: 'Galaxie',
    cat_clusters: 'Hvězdokupy',
    cat_nebulae: 'Mlhoviny',
    cat_planets: 'Planety',
    mercury: 'Merkur',
    venus: 'Venuše',
    mars: 'Mars',
    jupiter: 'Jupiter',
    saturn: 'Saturn',
    uranus: 'Uran',
    neptune: 'Neptun',
    faq: 'FAQ & Průvodce',
    backToApp: 'Zpět do aplikace',
    exportPDF: 'Exportovat do PDF',
    issFlyovers: 'Přelety ISS',
    iss_none: 'Žádné přelety v příštích 24h',
    iss_time: 'Čas',
    iss_duration: 'Délka',
    iss_maxAlt: 'Max. výška',
    faq_intro: 'Vítejte v průvodci Hvězdným Plánovačem. Tento nástroj vám pomůže naplánovat pozorování vesmíru i pokud jste začátečník.',
    faq_q1: 'Co jsou to Deep Sky objekty?',
    faq_a1: 'Jde o objekty vzdáleného vesmíru, které nejsou hvězdami ani planetami. Patří sem galaxie (miliardy hvězd), mlhoviny (mračna plynu a prachu) a hvězdokupy (shluky hvězd). V našem katalogu najdete 110 Messierových objektů – ty nejkrásnější, které lze spatřit amatérskými dalekohledy.',
    faq_q2: 'Co znamená "Výška nad obzorem" (Altitude)?',
    faq_a2: 'Je to úhel mezi objektem a vaším vodorovným obzorem. 0° znamená, že objekt je přímo na horizontu, 90° (zenit) znamená, že je přímo nad vaší hlavou. Pro nejlepší pozorování hledejte objekty s výškou nad 30°, kde je atmosféra nejtenčí.',
    faq_q3: 'K čemu slouží Mapa světelného znečištění?',
    faq_a3: 'Městské lampy "přesvětlují" oblohu, takže slabé galaxie nejsou vidět. Na mapě hledejte modré a černé oblasti – to jsou nejtmavší místa, kde uvidíte vesmír v plné kráse. Červené a bílé oblasti značí velká města se špatnou viditelností.',
    faq_q4: 'Co je to Magnituda?',
    faq_a4: 'Je to vědecký údaj o jasu objektu. Pozor: Čím je číslo NIŽŠÍ, tím je objekt JASNĚJŠÍ. Sirius má magnitudu -1,4, zatímco slabá galaxie může mít 9,0. Lidské oko vidí pod tmavou oblohou objekty do magnitudy cca 6,0.',
    faq_q5: 'Jak používat Graf výšky?',
    faq_a5: 'Graf ukazuje pohyb vybraného objektu po dobu 24 hodin. Nejvyšší bod na křivce značí čas, kdy je objekt nejlépe viditelný. Pokud je křivka pod nulou, objekt je pod obzorem a není vidět.',
    faq_q6: 'Co je Aladin Lite?',
    faq_a6: 'Je to integrovaný hvězdný atlas, který vám ukáže REÁLNOU fotografii z profesionálních teleskopů. Pomůže vám se zorientovat, jak daný objekt vypadá, než se ho pokusíte najít vlastním dalekohledem.',
    telescopeControl: 'Ovládání teleskopu (ASCOM Alpaca)',
    connect: 'Připojit',
    disconnect: 'Odpojit',
    slewTo: 'Najet teleskopem',
    community: 'Komunita',
    planner: 'Plánovač',
    loginSync: 'Cloud Sync',
    shareObservation: 'Sdílet pozorování',
    sharedBy: 'Sdílel(a)',
    ipAddress: 'IP Adresa',
    connected: 'Připojeno',
    nightMode: 'Noční režim (Červený)',
    gearSimulator: 'Kalkulačka optiky',
    focalLength: 'Ohnisko (mm)',
    eyepiece: 'Okulár (mm)',
    magnification: 'Zvětšení',
    exitPupil: 'Výstupní pupila',
    meteorShowers: 'Meteorické roje',
    recommendedFilter: 'Doporučený filtr',
    comets: 'Jasné komety',
    peakDate: 'Maximum',
    mm: 'mm',
    starMap: 'Interaktivní mapa oblohy',
    pixelSize: 'Velikost pixelu (μm)',
    resolution: 'Rozlišení',
    exposure: 'Odhad expozice',
    astroAsst: 'Astro-foto asistent',
    moonAsst: 'Měsíc a terminátor',
    visibleCraters: 'Dnes nejlépe viditelné krátery',
    issLive: 'Živé sledování ISS',
    sensorRes: 'Rozlišení senzoru (px)',
    sampling: 'Kvalita samplingu',
    guiding: 'Požadovaná pointace (RMS)',
    integration: 'Potřebná data (celkem)',
    optimal: 'Optimální',
    undersampled: 'Under-sampled',
    oversampled: 'Over-sampled',
  }
}
